services:
  questdb:
    image: questdb/questdb:latest
    container_name: questdb
    ports:
      - "8812:8812"  # PostgreSQL wire protocol
      - "9000:9000"  # Web Console & HTTP API
      - "9009:9009"  # InfluxDB line protocol
    volumes:
      - ./.volumes/questdb:/var/lib/questdb
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/exec?query=SELECT%201"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./.volumes/grafana:/var/lib/grafana
    depends_on:
      - questdb

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./.volumes/redis:/data
